name: Create Release on Tag Push

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          body: |
            ## 🚀 Release ${{ github.ref_name }}
            
            ### 📦 Installation
            
            ```kotlin
            repositories {
                maven { url = uri("https://jitpack.io") }
            }
            
            dependencies {
                implementation("com.github.zhuxietong:ky:${{ github.ref_name }}")
            }
            ```
            
            ### 📋 Changes
            See the [commits](https://github.com/${{ github.repository }}/commits/${{ github.ref_name }}) for details.
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
